version: "3.9"

services:
  db:
      image: postgres:15
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: wms_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./database/wms_dump.sql:/docker-entrypoint-initdb.d/wms_dump.sql
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wms_db
      DATABASE_URL_TEST: postgresql://postgres:postgres@db:5432/wms_db_test
      SECRET_KEY: tajny_klucz_123
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  postgres_data: