"""add indexes to columns

Revision ID: 76a7c5409f5d
Revises: 
Create Date: 2026-01-24 18:27:52.505323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76a7c5409f5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deliver_details_deliver_id'), 'deliver_details', ['deliver_id'], unique=False)
    op.create_index(op.f('ix_deliver_details_ean'), 'deliver_details', ['ean'], unique=False)
    op.create_index(op.f('ix_delivery_order_deliver_id'), 'delivery_order', ['deliver_id'], unique=False)
    op.create_index(op.f('ix_order_picking_details_order_id'), 'order_picking_details', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_picking_details_product_id'), 'order_picking_details', ['product_id'], unique=False)
    op.alter_column('orders', 'create_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_details_ean'), 'orders_details', ['ean'], unique=False)
    op.create_index(op.f('ix_orders_details_order_id'), 'orders_details', ['order_id'], unique=False)
    op.create_index(op.f('ix_picks_ean'), 'picks', ['ean'], unique=False)
    op.create_index(op.f('ix_picks_order_id'), 'picks', ['order_id'], unique=False)
    op.create_index(op.f('ix_product_details_ean'), 'product_details', ['ean'], unique=False)
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'jednostka',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'unit_weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('products', 'available_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_products_ean'), 'products', ['ean'], unique=False)
    op.create_index(op.f('ix_products_location'), 'products', ['location'], unique=False)
    op.alter_column('relocation', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_relocation_ean'), 'relocation', ['ean'], unique=False)
    op.create_index(op.f('ix_relocation_initial_location'), 'relocation', ['initial_location'], unique=False)
    op.create_index(op.f('ix_reservation_ean'), 'reservation', ['ean'], unique=False)
    op.alter_column('suppliers', 'supplier_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 1. Usuwamy indeksy (w odwrotnej kolejności niż w upgrade)
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_reservation_ean'), table_name='reservation')
    op.drop_index(op.f('ix_relocation_initial_location'), table_name='relocation')
    op.drop_index(op.f('ix_relocation_ean'), table_name='relocation')
    op.drop_index(op.f('ix_products_location'), table_name='products')
    op.drop_index(op.f('ix_products_ean'), table_name='products')
    op.drop_index(op.f('ix_product_details_ean'), table_name='product_details')
    op.drop_index(op.f('ix_picks_order_id'), table_name='picks')
    op.drop_index(op.f('ix_picks_ean'), table_name='picks')
    op.drop_index(op.f('ix_orders_details_order_id'), table_name='orders_details')
    op.drop_index(op.f('ix_orders_details_ean'), table_name='orders_details')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_order_picking_details_product_id'), table_name='order_picking_details')
    op.drop_index(op.f('ix_order_picking_details_order_id'), table_name='order_picking_details')
    op.drop_index(op.f('ix_delivery_order_deliver_id'), table_name='delivery_order')
    op.drop_index(op.f('ix_deliver_details_ean'), table_name='deliver_details')
    op.drop_index(op.f('ix_deliver_details_deliver_id'), table_name='deliver_details')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')

    # 2. Przywracamy nullable=True i stare typy
    op.alter_column('suppliers', 'supplier_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    
    op.alter_column('relocation', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Przywracamy nullable i precyzję dla produktów
    op.alter_column('products', 'available_amount', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('products', 'date', existing_type=sa.DATE(), nullable=True)
    op.alter_column('products', 'amount', existing_type=sa.INTEGER(), nullable=True)
    
    for col in ['jednostka', 'ean', 'product_name', 'code']:
        op.alter_column('products', col, existing_type=sa.VARCHAR(), nullable=True)

    op.alter_column('products', 'unit_weight',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    op.alter_column('orders', 'create_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
